name: Pipeline CI
on:
  pull_request:
   branches:
     - main
  push:
    branches:
      - main
jobs:
  Build_and_Test:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Compile
        run: pip install --no-cache-dir --upgrade -r requirements.txt
      - name: Test and coverage
        run: python -m coverage run -m unittest discover tests  &&  python -m coverage xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          
      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      - name: "Example show SonarQube Quality Gate Status value"
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"

      - name: Dockerhub login
        run: sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: sudo docker compose build 
      
      - name: Push to Dockerhub
        run: sudo docker push bakkym/fast-api:latest
        